### PR TITLE
turn_green_led(on=True) or turn_green_led(on=False)

### PR DESCRIPTION
**Pull request by cclauss**
Removes `turn_on_led_green()` and `turn_off_led_green()`.

### CODE REVIEW

**Comment by delirious-lettuce** [comment]
@cclauss ,

What about naming it ~~`toggle_led_green` or~~ `toggle_green_led`?

**Comment by cclauss** [comment]
"I toggled the green led on" is more correct English than
"I toggled the led green on". 

Although "I toggled on the green led" does work but forces you into two functions instead of one.

**Comment by delirious-lettuce** [comment]
@cclauss ,

Too bad Python 2 doesn't have keyword only args...

**Comment by cclauss** [comment]
Yes but turn_green_led(True) and turn_green_led(False) still makes sense.

**Comment by delirious-lettuce** [comment]
"Turn green led into a boat"?

It's just a bit ambiguous.

**Comment by delirious-lettuce** [comment]
### [toggle](https://dictionary.cambridge.org/dictionary/english/toggle)

> a key or button on a computer that is pressed to turn a feature on and then off

> to switch a feature on a computer on and off by pressing the same button or key

**Comment by delirious-lettuce** [comment]
In a way, it almost makes the original function names quite appealing. The ambiguity of using an unnamed boolean as a potential argument seems to be a downside.

`turn_on_led_green()` and `turn_off_led_green()` are quite descriptive. Although maybe `turn_on_green_led` and `turn_off_green_led` might be better?

**Pull request closed without merging**
